#!/bin/bash

program="dbsg"
wallpapers="$HOME/.$program/wallpapers.txt"
minutes=30
log="/var/log/$program.log"
conf="$HOME/.$program/$program.conf"
if [ -f $conf ]; then
    . $conf
else
    declare -a folders
fi

check_permission() {
    # Check if cron has thu permission to change the desktop background

    # Check if the system is using GNOME 3 as desktop environment
    xpid=$(pidof gnome-shell)
    if [ -z $xpid ]; then
        echo Sorry, this program is designed to work only in GNOME 3.
        exit 5
    fi

    # Tell cron what is the display currently used
    xdisp=$(awk 'BEGIN{RS="\\000";FS="="}($1 == "DISPLAY"){print $2}' \
        < /proc/$xpid/environ)
    export DISPLAY=$xdisp

    # Check if the file .Xauthority is present in the home folder of
    # the user
    if [ ! -f "$HOME/.Xauthority" ]; then
        cmd='[ "$XAUTHORITY" ] && cp -f "$XAUTHORITY" ~/.Xauthority'
        dest="$HOME/.xprofile"
        if [ ! -f "$HOME/.xprofile" ]; then
            echo $cmd > $dest
        else
			permitted=`more $dest | grep XAUTHORITY | wc -l`
	        if [ $permitted -eq 0 ]; then
                echo $cmd >> $dest
            fi
        fi
        echo Please reboot to let cron schedule the wallpaper slideshow
    fi
}

check_configuration_folder() {
    # Check if the configuration folder does exist

    if [ ! -d $HOME/.$program ]; then
        mkdir -p $HOME/.$program
    fi
}

update_slideshow() {
    # Use crontab to schedule the wallpaper slideshow by first backing up
    # the current crontab file

    . $conf
    tmp="$HOME/.$program/crontab.tmp"
    crontab -l | grep -Ev $program > $tmp
    echo "*/$minutes * * * * $program -c" >> $tmp
    crontab $tmp
}

check_schedule() {
    # Check if the wallpaper slideshow has been scheduled

    scheduled=`crontab -l | grep "dbsg -c" | wc -l`
	if [ $scheduled -eq 0 ]; then
    	update_slideshow
	fi
}

print_folders() {
    # Print the list of currently monitored folders

    if [ ${#folders[@]} -eq 0 ]; then
        echo -e "\n$program is not currently monitoring any folder.\n"
    else
        echo -e "\n$program is currently monitoring the following folders:\n"
    fi
	for folder in "${folders[@]}"; do
	    echo $folder
	done
}

add_folders() {
    # Add folders to be monitored

    check_configuration_folder
    check_permission
    check_schedule
    if [ -f $conf ]; then
        rm $conf
        print_folders
    fi
    echo -e "\nEnter the full path of the image folders that you"
    echo want to set as your desktop background.
    echo Please leave an empty line by pressing "<Enter>" when you
    echo have finished.
    
    declare -i i=${#folders[@]}
	while true; do
	    echo -e -n "\nFolder #$((i+1)): "
	    read folders[$i]
	    if [ -z ${folders[0]} ]; then
	        echo -e "\nPlease enter at least one folder."
	        i=i-1
	    elif [ ! -d ${folders[$i]} ]; then
	        echo This folder does not exist. Please enter a valid one.
	        i=i-1
	    elif [ -z ${folders[$i]} ]; then
	        break
	    fi
	    i=i+1
	done

    print_folders
	echo "folders=(${folders[@]})" > $conf
    update_wallpapers
    change_wallpaper
}

remove_folders() {
    # Remove folders to be monitored

    if [ -f $conf ]; then
        print_folders
    fi
    echo -e "\nEnter the full path of the image folders that you"
    echo "do not want to monitor anymore."
    echo Please leave an empty line by pressing "<Enter>" when you
    echo have finished.
    
	while true; do
	    echo -e -n "\nFolder: "
	    read removed_folder
	    if [ ! -d $removed_folder ]; then
	        echo This folder does not exist. Please enter a valid one.
        elif [ -z $removed_folder ]; then
	        break
        else
            declare -i j=0      
            monitored=false
            while [ $j -lt "${#folders[@]}" ]; do
                if [ "${folders[$j]}" = "$removed_folder" ]; then
                    monitored=true
                    break
                fi
                j=j+1
            done
            if [ ! $monitored ]; then
                echo "This folder is not currently monitored."
            else
                unset folders[$j]
            fi
        fi
	done

    print_folders
	echo "folders=(${folders[@]})" > $conf
    update_wallpapers
    change_wallpaper
}

check_folders() {
    # Check if all monitored folders do exist

    declare -i i=0
    while [ "${folders[$i]}" != "" ]; do
        if [ ! -d ${folders[$i]} ]; then
            echo '`date "+%Y-%M-%d, %H:%M"` - Folder "${folders[$i]}" 
                does not exist! Check $CONF' >> $log
            exit 2
        fi
        i=i+1
    done
}

check_wallpaper() {
    # Check if the wallpaper has been deleted

    if [ ! -f $1 ]; then
        echo File $1 has been deleted! >> $log
        update_wallpapers
    fi
}

update_wallpapers() {
    # Update wallpaper list

    if [ ${#folders[@]} -eq 0 ]; then
        add_folders
    elif [ -f $conf ]; then
        . $conf
    fi
    if [ -f $wallpapers ]; then
        rm $wallpapers
    fi
    echo "`date "+%Y-%M-%d, %H:%M"` - Adding wallpapers to the 
            list..." >> $log
    declare -i i=0
    while [ "${folders[$i]}" != "" ]; do
        for file in ${folders[$i]}/*.{jpg,JPG,bmp,BMP,png,PNG,tif,TIF,gif,GIF}; do
            echo $file >> $wallpapers
        done
        i=i+1
    done
	echo `date "+%Y-%M-%d, %H:%M"` - Wallpaper list updated! >> $log
}

get_current_wallpaper() {
    # Return the current desktop background

    echo `/usr/bin/gsettings get org.gnome.desktop.background picture-uri | 
            sed "s/'//g" | sed 's/file:\/\///'`
}

change_wallpaper() {
    # Change the current desktop background

    check_permission
    check_folders
    update_wallpapers
    lines=`cat $wallpapers | wc -l`
    line=$(( $RANDOM % $lines + 1 ))
    image=`head -$line $wallpapers | tail -1`
    check_wallpaper $image
    new="'file://$image'"
    gsettings set org.gnome.desktop.background picture-uri $new
    current=`get_current_wallpaper`
    if [ $image = $current ]; then
    	echo "`date "+%Y-%M-%d, %H:%M"` - Wallpaper successfully 
                changed!" >> $log
    	echo `date "+%Y-%M-%d, %H:%M"` - New wallpaper: $current >> $log
    else
        #This should never happen
    	echo "`date "+%Y-%M-%d, %H:%M"` - Wallpaper not changed! Try updating 
                the wallpaper list" >> $log
        exit 3
    fi
}

delete_current_wallpaper() {
    # Delete the image of the current desktop background

    current=`get_current_wallpaper`
    if [ ! -f $current ]; then
        echo "Error: the file does not exist."
        exit 4
    else
        rm $current
        echo File successfully removed.
        echo `date "+%Y-%M-%d, %H:%M"` - Wallpaper removed: $current >> $log
    fi
    change_wallpaper
}

number_of_wallpapers() {
    # Show the number of currently monitored wallpapers

    n=`more $wallpapers | wc -l`
    echo -e "\n$program is currently monitoring $n wallpapers.\n"
}

case "$1" in
    -a) add_folders;;
    -b) get_current_wallpaper;;
    -c) change_wallpaper;;
    -d) delete_current_wallpaper;;
    -i) initialize_slideshow;;
    -n) number_of_wallpapers;;
    -p) print_folders;;
    -r) remove_folders;;
     *) echo "usage: $program option"
        echo -e "\nPossible options are:"
        echo "  -a  add folders to be monitored"
        echo "  -b  show path of current desktop background"
        echo "  -c  change current desktop background"
        echo "  -d  delete file of current desktop background"
        echo "  -n  show number of monitored wallpapers"
        echo "  -p  print list of monitored folders"
        echo "  -r  stop monitoring specific folders"
        echo See the man page for more details.
esac
exit 0
